image:
  repository: registry.gitlab.com/eagledevstack/flask-app
  pullPolicy: IfNotPresent
  tag: "378818e2"

imagePullSecrets: []

replicaCount: 1

service:
  type: ClusterIP
  portName: flask-app-port
  protocol: TCP
  port: 5000
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  tls: []
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: Prefix

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
